change the securityContext as recommended by the SDK
kube-storage/volume-replication-operator pull request #8
Opened 2021-03-02 00:44 UTC by raghavendra-talur

2021-03-02 07:28 UTC, Madhu-1 approved these changes
LGTM. we can do the fixes and enhancements in follow-up PR's

2021-03-02 07:29 UTC, Madhu-1 requested changes
reviewed the wrong one.

2021-03-02 07:51 UTC, umangachapagain approved these changes

2021-03-02 08:10 UTC, sp98 approved these changes

2021-03-08 05:32 UTC, Madhu-1 commented
The change is already present in the main branch. closing this one now.

2021-03-08 05:32 UTC, closed without merging